version: '3.4'

services:
  backend:
    container_name: webapi
    tty: true 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app:rw,cached'
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DOT_USE_POLLING_FILE_WATCHER=1

  database:
    container_name: mysql
    image: mysql:8.0
    cap_add:
     - SYS_NICE
    environment:
     - MYSQL_DATABASE=root
     - MYSQL_ROOT_PASSWORD=daprey123
    ports:
     - '3306:3306'
    volumes:
     - /opt/mysql_data:/var/lib/mysql
